const DEFAULT_DEADLINE_HOURS = 24;

const REMINDER_INTERVALS = {
  LOW: 30,
  MEDIUM: 15,
  HIGH: 5,
  CRITICAL: 2,
};

const RANDOM_CHECKIN_CHANCE = 0.1;

const SCHEDULER_CRON = "* * * * *";

module.exports = {
  DEFAULT_DEADLINE_HOURS,
  REMINDER_INTERVALS,
  RANDOM_CHECKIN_CHANCE,
  SCHEDULER_CRON,
};
